name: RVOS CI (C only)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test RVOS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install RISC-V toolchain and QEMU
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          gcc-riscv64-unknown-elf \
          qemu-system-misc \
          gdb-multiarch \
          u-boot-tools \
          build-essential

    - name: Build OS kernel (C only)
      run: make all

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rvos-build
        path: |
          Image
