name: RVOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install RISC-V toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-riscv64-unknown-elf
        sudo apt-get install -y qemu-system-misc
        
    - name: Build OS kernel
      run: |
        make all
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rvos-build
        path: |
          build/os.elf
